Account/urls.py
from django.urls import path, re_path
from Account import views

app_name = 'Account'
urlpatterns = [
    path('register', views.register, name='register'),
    path('hotel_register', views.hotel_register, name='hotel_register'),
    path('save_register', views.save_register, name='save_register'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            views.activate, name='activate'),
    path('login', views.login, name='login'),
    path('loginn', views.loginn, name='loginn'),
    path('logout_view', views.logout_view, name='logout_view'),
    path('profile/', views.choose_profile, name='choose_profile'),


]

Frontend/urls.py
from django.urls import path
from Frontend import views

app_name = 'Frontend'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('cities', views.cities, name='cities'),
    path('view_more/<int:hotels_id>/', views.view_more, name='view_more'),
    path('<int:category_id>/<hotel_name>/reservation/', views.calendar, name='calendar'),
    path('findcity', views.findcity, name='findcity')

]

Hotel/urls.py
from django.urls import path
from Hotel import views

app_name = 'Hotel'
urlpatterns = [
    path('add-hotel', views.addhotel, name='add-hotel'),
    path('view/hotels/list', views.view_hotels_list, name='add-image'),
    # path('add-room/<int:hotel_id>/', views.add_room, name='add-room')
    path('view-hotels/<int:pk>/details', views.HotelDetails.as_view(), name='details'),
    path('add-images/<int:hotel_id>/', views.add_more_image, name='add_more_image'),
    path('add-room/<int:hotel_id>/', views.add_room, name='add-room'),
    path('room-categories/', views.room_categories, name='room-categories'),
    path('cities/<location>/', views.locations, name='locations'),
    path('<int:hotel_id>/add-room-images/', views.add_more_room_image, name='add_more_room_image')
    # path('lagos', views.lagos, name='lagos')
]

website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Frontend.urls', namespace='Frontend')),
    path('account/', include('Account.urls', namespace='Account')),
    path('customer/', include('Customer.urls', namespace='Customer')),
    path('hotel/', include('Hotel.urls', namespace='Hotel')),
    path('reservation/', include('Reservation.urls', namespace='Reservation'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Frontend/models.py
from django.db import models

# Create your models here.

Frontend/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from Account.models import UserInfo
from Hotel.models import HotelProfile, HotelPictures,  Room, RoomCategory, RoomPictures, RoomStatus
from Reservation.models import GuestReservation
from django.db.models import Q
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse


def homepage(request):
    return render(request, 'Frontend/home.html')


def aboutus(request):
    return render(request, 'Frontend/about.html')


def cities(request):
    lagos = HotelProfile.objects.filter(location='lagos')
    count_number_lagos = lagos.count()
    abuja = HotelProfile.objects.filter(location='abuja')
    count_number_abuja = abuja.count()
    owerri = HotelProfile.objects.filter(location='owerri')
    count_number_owerri = owerri.count()
    portharcourt = HotelProfile.objects.filter(location='portharcourt')
    count_number_of_portharcourt = portharcourt.count()
    delta = HotelProfile.objects.filter(location='delta')
    count_number_of_delta = delta.count()
    calabar = HotelProfile.objects.filter(location='calabar')
    count_number_of_calabar = calabar.count()
    uyo = HotelProfile.objects.filter(location='uyo')
    count_number_of_uyo = uyo.count()
    enugu = HotelProfile.objects.filter(location='enugu')
    count_number_of_enugu = enugu.count()
    kano = HotelProfile.objects.filter(location='kano')
    count_number_kano = kano.count()
    context = {'count_number_lagos': count_number_lagos, 'count_number_abuja': count_number_abuja,
               'count_number_owerri': count_number_owerri, 'count_number_portharcourt': count_number_of_portharcourt,
               'count_number_delta': count_number_of_delta, 'count_number_calabar': count_number_of_calabar,
               'count_number_uyo': count_number_of_uyo, 'count_number_enugu': count_number_of_enugu,
               'count_number_kano': count_number_kano}
    template = 'Frontend/cities.html'
    return render(request, template, context)


def view_more(request, hotels_id):
    get_hotel = HotelPictures.objects.filter(hotel__id=hotels_id)
    hotel_name = HotelProfile.objects.get(pk=int(hotels_id))
    room_category = RoomCategory.objects.filter(hotel_id=hotels_id).order_by('pk')
    context = {'get_hotel': get_hotel, 'room_category': room_category, 'hotel_name': hotel_name}
    return render(request, 'Frontend/view_more.html', context)


def calendar(request, category_id, hotel_name):
    current_user = request.user
    get_name = RoomCategory.objects.filter(pk=int(category_id))
    check_room = Room.objects.filter(room_type__in=get_name)
    if request.method == 'POST':
        check_In_Date = request.POST["date_in"]
        check_Out_Date = request.POST["date_out"]
        how_many_guests = request.POST["num_of_guests"]
        additional_request = request.POST["additional_info"]
        payment_type = request.POST["payment_type"]
        for rooms in check_room:
            if RoomStatus.objects.filter(starting_Date=check_In_Date,
                                         ending_Date=check_Out_Date,
                                         room_id=rooms.pk, occupationStatus='Occupied').exists():
                continue
            else:
                create_room_status = RoomStatus.objects.create(occupationStatus='Occupied',
                                                               starting_Date=check_In_Date,
                                                               ending_Date=check_Out_Date,
                                                               room_id=rooms.pk)
                create_room_status.save()
                user_info = UserInfo.objects.get(user=current_user)
                create_reservation = GuestReservation.objects.create(guest_id=user_info.pk, check_In_Date=check_In_Date,
                                                                     check_Out_Date=check_Out_Date,
                                                                     how_many_guests=how_many_guests,
                                                                     additional_request=additional_request,
                                                                     reserved_room_id=create_room_status.pk,
                                                                     payment_type=payment_type)
                create_reservation.save()
                msg = u'Successfully reserved room %s for %s' % (rooms.room_number, user_info.user.last_name)
                messages.success(request, msg)
                return HttpResponseRedirect(reverse('Frontend:calendar', kwargs={'category_id': category_id,
                                                                                 'hotel_name': hotel_name}))
        else:
            messages.warning(request, 'All rooms are currently occupied')
            return HttpResponseRedirect(reverse('Frontend:calendar', kwargs={'category_id': category_id,
                                                                             'hotel_name': hotel_name}))

    return render(request, 'Frontend/calendar.html', {'category_id': category_id, 'hotel_name': hotel_name})


def findcity(request):
    if request.method == 'POST':
        check_cities = request.POST["cities"]
        if HotelProfile.objects.filter(location=check_cities).exists():
            check_for_city = HotelProfile.objects.filter(location=check_cities)
            count_hotel = check_for_city.count()
            context = {
                'check_for_city': check_for_city,
                'count_hotel': count_hotel
            }
            return render(request, 'Frontend/findcity.html', context)
        else:
            messages.warning(request, 'City Unavailable')
            return redirect(request, 'Frontend:home')


#def display_actions(request,category_id):
 #   current_user = request.user
  #  get_identity = RoomCategory.objects.filter(pk=int(category_id))
   # context = {'current_user': current_user, 'get_identity': get_identity}
# return render(request, 'Frontend/display_actions.html', context)

website/templates/base/frontend/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hotel Management System {% block title %}{% endblock %}</title>
     <link rel="stylesheet" href="{%static 'bootstrap-4.1.1-dist/css/bootstrap.min.css'%}" type="text/css"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <style type="text/css">


}
    </style>
</head>
<body>
<!--NAVIGATION-->
<nav class = "navbar navbar-expand-md navbar-light bg-light sticky-top">
<div class ="container-fluid">
    <a class = "navbar-brand" href = "#"><img src = "{% static 'pictures/LOGO.png '%}" class="img-fluid"/></a>
    <button class="navbar-toggler" type ="button" data-toggle="collapse" data-target="#navbarResponsive">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'Frontend:homepage' %}">HOME</a>
            </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Frontend:aboutus' %}">ABOUT</a>
            </li>
            <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" href="#" id="hotel" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         HOTELS
        </a>
        <div class="dropdown-menu" aria-labelledby="hotel">
          <a class="dropdown-item" href="#">Lagos</a>
          <a class="dropdown-item" href="#">Abuja</a>
          <a class="dropdown-item" href="#">Owerri</a>
          <a class="dropdown-item" href="#">Port-Harcourt</a>
          <a class="dropdown-item" href="">Delta</a>
          <a class="dropdown-item" href="">Calabar</a>
          <a class="dropdown-item" href="">Uyo</a>
          <a class="dropdown-item" href="">Enugu</a>
          <a class="dropdown-item" href="">Ibadan</a>
          <a class="dropdown-item" href="">Kano</a>

        </div>
            </li>

            {% if request.user.is_authenticated %}

              <li class="nav-item">
                <a class="nav-link" href="{% url 'Account:choose_profile' %}">MY DASHBOARD</a>
            </li>
            {% else %}
              <li class="nav-item dropdown">
               <a class="nav-link" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         REGISTER
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'Account:register'%}">Guest</a>
          <a class="dropdown-item" href="{%url 'Account:hotel_register'%}">Hotel Owner</a>
        </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Account:login' %}">LOGIN </a>
            </li>
            {% endif %}
            <!----{% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{%url 'Account:logout_view'%}">LOGOUT </a>
            </li>
            {% else %}
             <li class="nav-item">
                <a class="nav-link" href="{% url 'Account:login' %}">LOGIN </a>
            </li>
            {% endif %}--->
        </ul>

    </div>
</div>
</nav>
{% block content %}{% endblock %}

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src = "https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
<script src="{%static 'bootstrap-4.1.1-dist/js/bootstrap.min.js' %}" type="text/javascript">
</script>
</html>