Frontend/urls.py
from django.urls import path
from Frontend import views

app_name = 'Frontend'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('cities', views.cities, name='cities'),
    path('view_more/<int:hotels_id>/', views.view_more, name='view_more'),
    path('<int:category_id>/<hotel_name>/reservation/', views.calendar, name='calendar'),
    path('findcity', views.findcity, name='findcity')

]

Hotel/urls.py
from django.urls import path
from Hotel import views

app_name = 'Hotel'
urlpatterns = [
    path('add-hotel', views.addhotel, name='add-hotel'),
    path('view/hotels/list', views.view_hotels_list, name='add-image'),
    # path('add-room/<int:hotel_id>/', views.add_room, name='add-room')
    path('view-hotels/<int:pk>/details', views.HotelDetails.as_view(), name='details'),
    path('add-images/<int:hotel_id>/', views.add_more_image, name='add_more_image'),
    path('add-room/<int:hotel_id>/', views.add_room, name='add-room'),
    path('room-categories/', views.room_categories, name='room-categories'),
    path('cities/<location>/', views.locations, name='locations'),
    path('<int:hotel_id>/add-room-images/', views.add_more_room_image, name='add_more_room_image')
    # path('lagos', views.lagos, name='lagos')
]

website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Frontend.urls', namespace='Frontend')),
    path('account/', include('Account.urls', namespace='Account')),
    path('customer/', include('Customer.urls', namespace='Customer')),
    path('hotel/', include('Hotel.urls', namespace='Hotel')),
    path('reservation/', include('Reservation.urls', namespace='Reservation'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hotel/models.py
from django.db import models
from Account.models import UserInfo
from django.conf import settings

CATEGORY_CHOICES = (
    ('lagos', 'LAGOS'),
    ('abuja', 'Abuja'),
    ('owerri', 'OWERRI'),
    ('portharcourt', 'PORTHARCOURT'),
    ('delta', 'DELTA'),
    ('calabar', 'CALABAR'),
    ('uyo', 'UYO'),
    ('enugu', 'ENUGU'),
    ('owerri', 'OWERRI'),
    ('kano', 'KANO'),
)


class HotelProfile(models.Model):
    admin = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    hotel_name = models.CharField(max_length=200)
    hotel_address = models.CharField(max_length=200, null=True)
    # hotel_logistics = models.CharField(max_length=100)
    hotel_contact = models.CharField(max_length=20, null=True)
    brief_description = models.CharField(max_length=200, null=True)
    location = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='select state')

    def __str__(self):
        return self.hotel_name


class Reception(models.Model):
    reception = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    hotel = models.ForeignKey(HotelProfile, on_delete=models.CASCADE)


class Room(models.Model):
    room_type = models.ForeignKey('Hotel.RoomCategory', on_delete=models.CASCADE, null=True, blank=True)
    # room_rate = models.CharField(max_length=200, null=True, blank=True)
    room_description = models.CharField(max_length=200, null=True, blank=True)
    room_bed_type = models.CharField(max_length=25)
    room_number = models.CharField(max_length=25, null=True, blank=True)
    hotel = models.ForeignKey(HotelProfile, on_delete=models.CASCADE)

    def __str__(self):
        return u'%s: %s' % (self.hotel, self.room_type)


class RoomCategory(models.Model):
    category_name = models.CharField(max_length=50)
    category_descriptions = models.CharField(max_length=500)
    room_rate = models.CharField(max_length=200, null=True, blank=True)
    admin = models.ForeignKey(UserInfo, on_delete=models.CASCADE, null=True, blank=True)
    hotel = models.ForeignKey(HotelProfile, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
         return u'%s:  %s' % (self.admin, self.category_name)


room_status = (
    ('Available', 'Available'),
    ('Occupied', 'Occupied'),
)


class RoomStatus(models.Model):
    occupationStatus = models.CharField(max_length=40, choices=room_status)
    starting_Date = models.DateTimeField()
    ending_Date = models.DateTimeField()
    status_UpdateTime = models.DateTimeField(auto_now_add=True)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)


class HotelPictures(models.Model):
    picture_Date = models.DateTimeField(auto_now_add=True)
    image_name = models.CharField(max_length=100, null=True)
    hotel = models.ForeignKey(HotelProfile, on_delete=models.CASCADE)
    hotel_image = models.FileField(upload_to='Hotel/Hotel/Pictures/', null=True)

    def __str__(self):
        return u'%s - %s' % (self.hotel.hotel_name, self.image_name)


class RoomPictures(models.Model):
    picture_Date = models.DateTimeField(auto_now_add=True)
    roomcategory = models.ForeignKey(RoomCategory, on_delete=models.CASCADE, null=True, blank=True)
    room_image_name = models.CharField(max_length=50, null=True, blank=True)
    room_image = models.FileField(upload_to='Hotel/Room/Pictures/')

Hotel/forms.py
from django import forms
from .models import HotelProfile, HotelPictures, RoomCategory


class HotelForm(forms.ModelForm):
    class Meta:
        model = HotelProfile
        exclude = ('admin',)
        fields = ('hotel_name', 'hotel_address', 'hotel_contact', 'brief_description', 'location')

        widgets = {
            'hotel_name': forms.TextInput(attrs={'class': 'form-control'}),
            #  'hotel_image': forms.FileInput(attrs={'class': 'default form-control'}),
            'hotel_address': forms.TextInput(attrs={'class': 'form-control'}),
            'hotel_contact': forms.TextInput(attrs={'class': 'form-control'}),
            'brief_description': forms.TextInput(attrs={'class': 'form-control'}),
            'location': forms.Select(attrs={'class': 'form-control'})
        }


class HotelImageForm(forms.ModelForm):
    class Meta:
        model = HotelPictures
        exclude = ('Hotel',)
        fields = ('image_name', 'hotel_image')

        widgets = {
            'image_name': forms.TextInput(attrs={'class': 'form-control'}),
            'hotel_image': forms.FileInput(attrs={'class': 'form-control'})
        }


class RoomCategoriesForm(forms.ModelForm):
    class Meta:
        model = RoomCategory
        exclude = ('admin', 'hotel')
        fields = ['category_name', 'category_descriptions', 'room_rate']

        widgets = {
            'category_name': forms.TextInput(attrs={'class': 'form-control'}),
            'room_rate': forms.TextInput(attrs={'class': 'form-control'}),
            'category_descriptions': forms.Textarea(attrs={'class': 'form-control'})
        }

Hotel/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from .forms import HotelForm
from django.contrib.auth.decorators import login_required
from Account.models import UserInfo
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect
from .forms import HotelImageForm, RoomCategoriesForm
from .models import HotelPictures, HotelProfile, Room, RoomPictures, RoomCategory


@login_required
def addhotel(request):
    form = HotelForm()
    if request.method == 'POST':
        image_name = request.POST["image"]
        image = request.FILES["image2"]
        admin = UserInfo.objects.get(user=request.user)
        form = HotelForm(request.POST, request.FILES)
        if form.is_valid():
            hotel = form.save(commit=False)
            hotel.admin = admin
            hotel.save()
            addhot = HotelPictures.objects.create(hotel_id=hotel.pk, image_name=image_name, hotel_image=image)
            addhot.save()
            messages.success(request, 'Successfully created Hotel')
            return HttpResponseRedirect(reverse('Hotel:add-image'))
    return render(request, 'Hotel/add-hotel.html', {'form': form})


@login_required
def view_hotels_list(request):
    template = 'Hotel/upload.html'
    user = UserInfo.objects.get(user=request.user)
    hotels = HotelProfile.objects.filter(admin=user)
    return render(request, template, {'hotels': hotels})


@login_required
def details(request, hotel_id):
    user = UserInfo.objects.get(user=request.user)
    hot = HotelProfile.objects.get(pk=int(hotel_id), admin=user)
    messages.success(request, 'Successfully Added Image. Kindly add few other '
                              'Hotel images(i.e Lobby,Swimming pool,Gym etc)')
    return redirect('Hotel:details', hotel_id=hotel_id)


class HotelDetails(DetailView):
    perms_to_check = ['Account.hotel']
    model = HotelProfile
    template_name = 'Hotel/details.html'
    context_object_name = 'hotel'

    def get_context_data(self, **kwargs):
        context = super(HotelDetails, self).get_context_data(**kwargs)
        image = HotelPictures.objects.filter(hotel=self.object) if HotelPictures.objects.filter(hotel=self.object).exists() else None
        context['hotel_image'] = image
        print('-------------------------')
        print(image)
        context['room_types'] = RoomCategory.objects.filter(admin=self.object.admin) if RoomCategory.objects.filter(admin=self.object.admin).exists() else None
        context['room'] = Room.objects.filter(hotel=self.object) if Room.objects.filter(hotel=self.object).exists() else None

        return context


@login_required
def dshboard(request):
    template = 'Profile/dshboard.html'
    return render(request, template)


@login_required
def add_more_image(request, hotel_id):
    if request.method == 'POST':
        image = request.POST['image']
        image2 = request.FILES['image2']
        if image == "" or image2 == "":
            messages.warning(request, 'All Field is Required.')
            return redirect('Hotel:details', pk=hotel_id)
        else:
            save_image = HotelPictures.objects.create(hotel_id=int(hotel_id), image_name=image, hotel_image=image2)
            save_image.save()
            messages.success(request, 'Successfully Added Image. Kindly add more Hotel images'
                                      '(i.e Lobby,Swimming pool,Gym etc)')
            return redirect('Hotel:details', pk=hotel_id)


@login_required
def room_categories(request):
    user = UserInfo.objects.get(user=request.user)
    hotels = HotelProfile.objects.filter(admin=user)
    form = RoomCategoriesForm()
    if request.method == 'POST':
        user = UserInfo.objects.get(user=request.user)
        form = RoomCategoriesForm(request.POST)
        hotel = int(request.POST['hotel'])
        if form.is_valid:
            room_category = form.save(commit=False)
            room_category.hotel_id = hotel
            room_category.admin_id = user.pk
            room_category.save()
            messages.success(request, 'Category successfully created')
            return redirect('Hotel:room-categories')
    return render(request, 'Hotel/room-categories.html', {'form': form,
                                                          'hotels': hotels})


@login_required
def add_room(request, hotel_id):
    if request.method == 'POST':
        roomtype = request.POST['room_type']
        rate = request.POST['room_rate']
        description = request.POST['room_description']
        number = request.POST['room_number']
        imgname = request.POST['room_image_name']
        bed = request.POST['room_bed_type']
        img = request.FILES['room_image']

        if roomtype != '':
            room_cat = RoomCategory.objects.get(category_name=roomtype)

            create_room = Room.objects.create(room_type=room_cat, room_rate=rate, room_description=description,
                                              room_number=number, room_bed_type=bed, hotel_id=int(hotel_id))
            create_room.save()
            create_roompictures = RoomPictures.objects.create(room_image_name=imgname, room_image=img,
                                                              roomcategory=room_cat)
            create_roompictures.save()
        else:
            messages.success(request, 'Kindly go to the roomCategory page and add a category  ')
            return redirect('Hotel:details', pk=int(hotel_id))
        messages.success(request, 'Room successfully created!')
        return redirect('Hotel:details', pk=int(hotel_id))
    return redirect('Hotel:details', pk=int(hotel_id))


@login_required
def add_more_room_image(request, hotel_id):
    if request.method == 'POST':
        room_pk = request.POST['status']
        room_image_name = request.POST['room_image_name']
        room_image = request.FILES['room_image']
        if room_image_name == "" or room_image == "":
            messages.warning(request, 'All Field is Required.')
            return redirect('Hotel:details', pk=hotel_id)
        else:
            save_image = RoomPictures.objects.create(roomcategory_id=int(room_pk), room_image_name=room_image_name,
                                                     room_image=room_image)
            save_image.save()
            messages.success(request, 'Successfully Added Image. You can add few more images)')
            return redirect('Hotel:details', pk=hotel_id)


def locations(request, location):
    state = HotelProfile.objects.filter(location=location)
    template = 'Hotel/locations.html'
    context = {'locations': state}
    return render(request, template, context)

Hotel/templates/Hotel/abuja.html
{% extends 'base/frontend/base.html' %}
{% load static %}

{% block content %}
<div class="container" style="padding-top:15px" >
    <div class="row">
        {% for hotels in display_hotels %}
        <div class="col-md-4">
            <div class="card">
                <a href="#"><img src="{{hotels.hotel_image.url}}" class="card-img-top img-fluid"style="height:180px"> </a>
                <div class="card-body">
                    <h3>{{hotels.hotel_name}}</h3>
                    <hr>
                    <h5>{{hotels.brief_description}}</h5>
                    <div class="col-lg-6 offset-3">
                    <a href="#"class="btn btn-primary">View Hotel</a>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock%}

Hotel/templates/Hotel/add-hotel.html
{% extends 'Customer/dashboard.html' %}

{% load static %}
{% block title_page %} LBMG::Add Hotel Details {% endblock %}
{% block page_title %} Add Hotel Details {% endblock %}

{% block content %}
<div class="container">
  <!--<h3>LBMG</h3>-->
  <!---<ul class="nav nav-pills nav nav-justified">
    <li class="active"><a href="#" data-toggle="tab">HOTEL</a></li>
    <li><a href="#" data-toggle="tab">UPLOAD IMAGES</a></li>
  </ul>--->
    <div class="tab-content"></div>
<div class="content">
        <div class="row">
            <div class="col-lg-1">&nbsp;</div>
          <div class="col-lg-10">
            <div class="card card-chart">
              <div class="card-header">
                <h5 class="card-category" style="text-align:center">Create Hotel</h5>
              </div>
              <div class="card-body">
                <form method="post" action="{% url 'Hotel:add-hotel' %}" class="form-horizontal" enctype="multipart/form-data">
                  {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                  <label for="{{ field.id }}" class="control-label col-sm-2">{{ field.label }}: </label>
                  <div class="col-sm-9">
                    {{ field }}
                  </div>
                  {{ field.errors }}
                </div>
                {% endfor %}
                    <div class="form-group col-md-9">
                      <label>Image-Name:</label>
                      <input type="text" class="form-control" name="image">
                    </div>
                 <div class="col-md-9">
                     <label>Add Image:</label>
                     <input type="file" class="form-control" name="image2"/>
                 </div>
                 <input type="submit" class="btn btn-primary pull-right"/>
                  </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

Hotel/templates/Hotel/details.html
{% extends 'base/backend/base.html' %}

{% load static %}
{% load staticfiles %}
{% block title %} Hotel Details {% endblock %}
{% block page_title %} Add Hotel Details {% endblock %}

{% block content %}
<style>
  #zoom:hover;
  #zoom:active;
  #zoom:focus {
  -ms-transform:scale(2.0);
  -moz-transform:scale(2.0);
  -webkit-transform:scale(2.0);
  -o-transform:scale(2.0);
  position:relative;
  z-index:100;
  }

</style>
 <div class="container">
    <div class="row">
            <div class="col-md-8 offset-2">
            {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert" style="background-color: whitesmoke; box-shadow: 10px 10px 10px;color:darkgray">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
   <p style="color:red">{{ message }}</p>
        {% endfor %}
        </div>
    </div>
    </div>
    <div class="col-md-10 offset-1" style="margin-top:1%">
    <div class="card">
   <div class="row">
     <div class="card-body">
         <div class="col-md-6 offset-3">
              <!--<div class="row">-->
                     <!--<div class="col-md-4">-->
                        <!--<img src="{{ hotel_image.hotel_image.url|first }}" class="img-fluid" style="height:200px; width:1000px" >-->
                     <!--</div>-->
             <!--</div>-->
         </div>
<table class="table table-hover table-light" style="margin-top1%">
  <tbody>
  <tr>
      <th>Hotel Name:</th>
    <td>{{ hotel.hotel_name }}</td>
  </tr>
  <tr>
    <th>Brief Description:</th>
    <td>{{ hotel.brief_description }}</td>
  </tr>
  <tr>
    <th>Address:</th>
    <td>{{ hotel.hotel_address }}</td>
  </tr>
   <tr>
    <th>Contact:</th>
    <td>{{ hotel.hotel_contact }}</td>
  </tr>
     <tr>
    <th>Location:</th>
    <td>{{ hotel.location }}</td>
  </tr>
</table>
     </div>
   </div>
    </div>
    </div>
 <div class="col-md-10 offset-1">
    <div class="card">
     <div class="card-body">
         <div class="row">
         <div class="col-md-6" >
             <div class="row col-md-10 offset-1">.
                 <button type="button" class="btn btn-info" data-toggle="modal" data-target="#exampleModal"
                         onclick="addRoomImage('{{ rooms.pk }}')"><i class="fas fa-plus-square"></i>
                     Add Room
                 </button>
             </div>
                 <table class="table table-hover table-light" style="margin-top:4%">

                      <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Room Category</th>
                            <th scope="col">Room Number</th>
                            <th scope="col"> Add Room Image</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for rooms in room %}
                        <tr>
                            <td scope="row">{{ forloop.counter }}</td>
                            <td>{{ rooms.room_type.category_name }}</td>
                             <td>{{ rooms.room_number }}</td>
                         <td>
                           <button type="button" class="btn btn-info" data-toggle="modal" data-target="#examModal" onclick="getRoomPK('{{ rooms.room_type.pk }}')">
                              Add Room Image
                            </button>
                         </td>
                        </tr>
                      {% endfor %}
                      </tbody>
             </table>
              </div>
             <div class="col-md-6">
                 <!-- Button trigger modal -->
<button type="button" class="btn btn-info" data-toggle="modal" data-target="#examplModal">
  Add More Hotel Image:
</button>

<!-- Modal -->
<div class="modal fade" id="examplModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
         <form action="{% url 'Hotel:add_more_image' hotel.pk %}" method="post" enctype="multipart/form-data">
         {% csrf_token %}
     <div class="form-group col-md-9">
         <label>Image Name:</label>
         <input type="text" class="form-control" name="image">
     </div>
        <div class="col-md-9">
            <label>Add More Hotel Image:</label>
            <input type="file" class="form-control" name="image2"/>
        </div>
     <div class="col-md-9" style="margin-top:1%">
        <input type="submit" class="btn btn-info pull-right"/>
     </div>
     </form>
      </div>
    </div>
  </div>
</div>
                 <table class="table table-hover table-light" style="margin-top:4%">
                      <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Image Name</th>
                            <th scope="col">View</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for images in hotel_image %}
                        <tr>
                            <td scope="row">{{ forloop.counter }}</td>
                            <td>{{ images.image_name }}</td>
                            <td>
                                <a href="{{ images.hotel_image.url }}" class="btn btn-light btn-md" target="_blank">
                                    <i class="far fa-eye"></i> View
                                </a>
                            </td>
                        </tr>
                      {% endfor %}
                      </tbody>
                 </table>
         </div>

   </div>
    </div>
 </div>
<br/>
     <form action="{% url 'Hotel:add_more_image' hotel.pk %}" method="post" enctype="multipart/form-data">

     </form>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">ADD ROOM</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
           <form action="{% url 'Hotel:add-room' hotel.pk %}" method="post" enctype="multipart/form-data">
         {% csrf_token %}

               <div class="form-group col-md-9">
                   <label>Room Category:</label>
                  <select name="room_type" class="form-control">
                      {% if room_types %}
                          {% for room_type in room_types %}
                          <option value="{{ room_type.category_name }}">{{ room_type.category_name }}</option>
                          {% endfor %}
                      {% else %}
                        <option>no categories created</option>
                      {% endif %}
                  </select>
                   <!--<input type="text" class="form-control" aria-label="Text input with dropdown button">-->
                </div>
                <div class="form-group col-md-9">
                    <label>Room Rate:</label>
                    <input type="text" class="form-control" name="room_rate"required>
                </div>
                <div class="form-group col-md-9">
                    <label>Room Description:</label>
                    <input type="text" class="form-control" name="room_description"required>
                </div>
                 <div class="form-group col-md-9">
                    <label>Bed Type:</label>
                    <input type="text" class="form-control" name="room_bed_type" required>
               </div>
                 <div class="form-group col-md-9">
                    <label>Room Number:</label>
                    <input type="text" class="form-control" name="room_number" required>
               </div>
                <div class="form-group col-md-9">
                    <label>Image Name:</label>
                    <input type="text" class="form-control" name="room_image_name"required>
               </div>
               <div class="col-md-9">
                    <label>Add Room Image:</label>
                    <input type="file" class="form-control" name="room_image" required/>
               </div>
               <div class="col-md-9" style="margin-top:1%">
                    <input type="submit" class="btn btn-info pull-right"/>
               </div>
            </form>
      </div>
     <!-- <div class="modal-footer">
        <button type="button" class="btn btn-primary">Save changes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>-->
    </div>
  </div>
</div>
 </div>
 </div>

<!-- Modal To add more room images -->
<div class="modal fade" id="examModal" tabindex="-1"  role="dialog" aria-labelledby="examplModalLabel" aria-hidden="true" >
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title">Add Room Image</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                  <span aria-hidden="true">&times;</span>
                                                </button>
                                              </div>
                                            <form action="{% url 'Hotel:add_more_room_image' hotel.pk %}" class="form-horizontal" method="post" enctype="multipart/form-data">
                                                <div class="modal-body">
                                                    {% csrf_token %}
                                                    <input type="hidden" id="status" name="status">
                                                    <div class="form-group">
                                                        <label for="room_image_name" class="control-label col-sm-6">Room Image Name: </label>
                                                        <div class="col-sm-8">
                                                            <input type="text" class="form-control" id="room_image_name" name="room_image_name">
                                                        </div>
                                                    </div>
                                                     <div class="form-group">
                                                        <label for="room_image" class="control-label col-sm-6">Add Room Image: </label>
                                                        <input type="file" class="form-control" id="room_image" name="room_image"/>
                                                    </div>

                                                </div>
                                                <div class="modal-footer">
                                                    <input type="submit" class="btn btn-info" value="Submit">
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
<!-- End Modal -->

{% endblock %}

{% block js %}
    <script>
          function getRoomPK(pk) {
            $('#status').val(pk);
          }
    </script>
{% endblock %}

Hotel/templates/Hotel/hotels.html
{% extends 'base/frontend/base.html' %}
{% load static %}

{% block content %}
<div class="container" style="padding-top:15px" >
    <div class="row">
        {% for hotels in display_hotels %}
        <div class="col-md-4">
            <div class="card">
                <a href="#"><img src="{{hotels.hotel_image.url}}" class="card-img-top img-fluid"style="height:180px"> </a>
                <div class="card-body">
                    <h3>{{hotels.hotel_name}}</h3>
                    <hr>
                    <h5>{{hotels.brief_description}}</h5>
                    <div class="col-lg-6 offset-3">
                    <a href="#"class="btn btn-primary">View Hotel</a>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock%}

Hotel/templates/Hotel/locations.html
{% extends 'base/frontend/base.html' %}
{% load static %}
{% load hotel_tags %}

{% block content %}
<div class="container" style="padding-top:15px" >
    <div class="row">

        <div class="col-md-4">
            {% for hotels in locations %}
                <div class="card">
                    {% for pic in hotels.pk|get_pictures %}
                        <a href="#"><img src="{{ pic.hotel_image.url }}" class="card-img-top img-fluid"style="height:180px"> </a>
                    {% endfor %}
                    <div class="card-body">
                        <h3>{{hotels.hotel_name}}</h3>
                        <hr>
                        <h5>{{hotels.brief_description}}</h5>
                        <div class="col-lg-6 offset-3">
                            <a href="{% url 'Frontend:view_more' hotels.id%}"class="btn btn-primary">View Hotel</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock%}

Hotel/templates/Hotel/owerri.html
{% extends 'base/frontend/base.html' %}
{% load static %}

{% block content %}
<div class="container" style="padding-top:15px" >
    <div class="row">
        {% for hotels in display_hotels %}
        <div class="col-md-4">
            <div class="card">
                <a href="#"><img src="{{hotels.hotel_image.url}}" class="card-img-top img-fluid"style="height:180px"> </a>
                <div class="card-body">
                    <h3>{{hotels.hotel_name}}</h3>
                    <hr>
                    <h5>{{hotels.brief_description}}</h5>
                    <div class="col-lg-6 offset-3">
                    <a href="#"class="btn btn-primary">View Hotel</a>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock%}