Frontend/urls.py
from django.urls import path
from Frontend import views

app_name = 'Frontend'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('cities', views.cities, name='cities'),
    path('view_more/<int:hotels_id>/', views.view_more, name='view_more'),
    path('<int:category_id>/<hotel_name>/reservation/', views.calendar, name='calendar'),
    path('findcity', views.findcity, name='findcity')

]

Hotel/urls.py
from django.urls import path
from Hotel import views

app_name = 'Hotel'
urlpatterns = [
    path('add-hotel', views.addhotel, name='add-hotel'),
    path('view/hotels/list', views.view_hotels_list, name='add-image'),
    # path('add-room/<int:hotel_id>/', views.add_room, name='add-room')
    path('view-hotels/<int:pk>/details', views.HotelDetails.as_view(), name='details'),
    path('add-images/<int:hotel_id>/', views.add_more_image, name='add_more_image'),
    path('add-room/<int:hotel_id>/', views.add_room, name='add-room'),
    path('room-categories/', views.room_categories, name='room-categories'),
    path('cities/<location>/', views.locations, name='locations'),
    path('<int:hotel_id>/add-room-images/', views.add_more_room_image, name='add_more_room_image')
    # path('lagos', views.lagos, name='lagos')
]

website/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls import include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Frontend.urls', namespace='Frontend')),
    path('account/', include('Account.urls', namespace='Account')),
    path('customer/', include('Customer.urls', namespace='Customer')),
    path('hotel/', include('Hotel.urls', namespace='Hotel')),
    path('reservation/', include('Reservation.urls', namespace='Reservation'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Frontend/models.py
from django.db import models

# Create your models here.

Frontend/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from Account.models import UserInfo
from Hotel.models import HotelProfile, HotelPictures,  Room, RoomCategory, RoomPictures, RoomStatus
from Reservation.models import GuestReservation
from django.db.models import Q
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse


def homepage(request):
    return render(request, 'Frontend/home.html')


def aboutus(request):
    return render(request, 'Frontend/about.html')


def cities(request):
    lagos = HotelProfile.objects.filter(location='lagos')
    count_number_lagos = lagos.count()
    abuja = HotelProfile.objects.filter(location='abuja')
    count_number_abuja = abuja.count()
    owerri = HotelProfile.objects.filter(location='owerri')
    count_number_owerri = owerri.count()
    portharcourt = HotelProfile.objects.filter(location='portharcourt')
    count_number_of_portharcourt = portharcourt.count()
    delta = HotelProfile.objects.filter(location='delta')
    count_number_of_delta = delta.count()
    calabar = HotelProfile.objects.filter(location='calabar')
    count_number_of_calabar = calabar.count()
    uyo = HotelProfile.objects.filter(location='uyo')
    count_number_of_uyo = uyo.count()
    enugu = HotelProfile.objects.filter(location='enugu')
    count_number_of_enugu = enugu.count()
    kano = HotelProfile.objects.filter(location='kano')
    count_number_kano = kano.count()
    context = {'count_number_lagos': count_number_lagos, 'count_number_abuja': count_number_abuja,
               'count_number_owerri': count_number_owerri, 'count_number_portharcourt': count_number_of_portharcourt,
               'count_number_delta': count_number_of_delta, 'count_number_calabar': count_number_of_calabar,
               'count_number_uyo': count_number_of_uyo, 'count_number_enugu': count_number_of_enugu,
               'count_number_kano': count_number_kano}
    template = 'Frontend/cities.html'
    return render(request, template, context)


def view_more(request, hotels_id):
    get_hotel = HotelPictures.objects.filter(hotel__id=hotels_id)
    hotel_name = HotelProfile.objects.get(pk=int(hotels_id))
    room_category = RoomCategory.objects.filter(hotel_id=hotels_id).order_by('pk')
    context = {'get_hotel': get_hotel, 'room_category': room_category, 'hotel_name': hotel_name}
    return render(request, 'Frontend/view_more.html', context)


def calendar(request, category_id, hotel_name):
    current_user = request.user
    get_name = RoomCategory.objects.filter(pk=int(category_id))
    check_room = Room.objects.filter(room_type__in=get_name)
    if request.method == 'POST':
        check_In_Date = request.POST["date_in"]
        check_Out_Date = request.POST["date_out"]
        how_many_guests = request.POST["num_of_guests"]
        additional_request = request.POST["additional_info"]
        payment_type = request.POST["payment_type"]
        for rooms in check_room:
            if RoomStatus.objects.filter(starting_Date=check_In_Date,
                                         ending_Date=check_Out_Date,
                                         room_id=rooms.pk, occupationStatus='Occupied').exists():
                continue
            else:
                create_room_status = RoomStatus.objects.create(occupationStatus='Occupied',
                                                               starting_Date=check_In_Date,
                                                               ending_Date=check_Out_Date,
                                                               room_id=rooms.pk)
                create_room_status.save()
                user_info = UserInfo.objects.get(user=current_user)
                create_reservation = GuestReservation.objects.create(guest_id=user_info.pk, check_In_Date=check_In_Date,
                                                                     check_Out_Date=check_Out_Date,
                                                                     how_many_guests=how_many_guests,
                                                                     additional_request=additional_request,
                                                                     reserved_room_id=create_room_status.pk,
                                                                     payment_type=payment_type)
                create_reservation.save()
                msg = u'Successfully reserved room %s for %s' % (rooms.room_number, user_info.user.last_name)
                messages.success(request, msg)
                return HttpResponseRedirect(reverse('Frontend:calendar', kwargs={'category_id': category_id,
                                                                                 'hotel_name': hotel_name}))
        else:
            messages.warning(request, 'All rooms are currently occupied')
            return HttpResponseRedirect(reverse('Frontend:calendar', kwargs={'category_id': category_id,
                                                                             'hotel_name': hotel_name}))

    return render(request, 'Frontend/calendar.html', {'category_id': category_id, 'hotel_name': hotel_name})


def findcity(request):
    if request.method == 'POST':
        check_cities = request.POST["cities"]
        if HotelProfile.objects.filter(location=check_cities).exists():
            check_for_city = HotelProfile.objects.filter(location=check_cities)
            count_hotel = check_for_city.count()
            context = {
                'check_for_city': check_for_city,
                'count_hotel': count_hotel
            }
            return render(request, 'Frontend/findcity.html', context)
        else:
            messages.warning(request, 'City Unavailable')
            return redirect(request, 'Frontend:home')


#def display_actions(request,category_id):
 #   current_user = request.user
  #  get_identity = RoomCategory.objects.filter(pk=int(category_id))
   # context = {'current_user': current_user, 'get_identity': get_identity}
# return render(request, 'Frontend/display_actions.html', context)

Frontend/templates/Frontend/about.html
{% extends 'base/frontend/base.html' %}
{% load static %}
    {% block title %} - About{% endblock %}
    {% block content %}

<html lang="en">
<body>
<h1>About Us</h1>
<img src = "{% static 'pictures/lobby.jpg '%}" width="100%"></br>
<p>
    We are an online hotel Management Agency specialised in hotel bookings within Nigeria.
    We help customers reserve good, clean and safe hotel rooms online, providing comprehensive help and support to our
    clients and making the hotel booking process hassle free.
</p>
<h3>Mission</h3>
<p>To enhance knowledge and Provide a platform for Nigerians and Africans at large.</p>

<h3>Vision</h3>
<p>To become the Most reliable and biggest provider of hotel information and reservation in Nigeria</p>

<h3>Values</h3>
<p>   We are an online hotel Management Agency specialising in hotel bookings within Nigeria.
    We help customers reserve good, clean and safe hotel rooms online, providing comprehensive help and support to our
    clients and making the hotel booking process hassle free.</p>

</body>
</html>
{% endblock %}

Frontend/templates/Frontend/cities.html
{% extends 'base/frontend/base.html' %}
{% load static %}
    {% block content %}
<style>
    .centered {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
</style>
<div class ="container-fluid">
    <div class="row" style="margin-top:1%" >
        <div class="col-sm-4">
            <a href="{% url 'Hotel:locations' 'lagos' %}"> <img src = "{% static 'pictures/lagos.jpg '%}" class="img-fluid" style="height:300px; width:100%"></a>
            <div class="centered">
                <a href="{% url 'Hotel:locations' 'lagos' %}" style="text-decoration:none;color:#FFBFFF; font-size:x-large"><strong>LAGOS</strong></a>
                <h3 style="color:#FFBFFF">&nbsp;&nbsp;&nbsp;{{count_number_lagos}}</h3>
            </div>
        </div>
         <div class="col-sm-4">
            <a href="{% url 'Hotel:locations' 'abuja' %}"><img src = "{% static 'pictures/abuja.jpg '%}" class="img-fluid" style="height:300px; width:100%"></a>
             <div class="centered">
                <a href="{% url 'Hotel:locations' 'abuja' %}" style="text-decoration:none;color:#FFBFFF; font-size:x-large"><strong>ABUJA</strong></a>
                <h3 style="color:#FFBFFF">&nbsp;&nbsp;&nbsp;{{count_number_abuja}}</h3>
            </div>
         </div>
             <div class="col-sm-4">
                <img src = "{% static 'pictures/owerri.jpg '%}" class="img-fluid" style="height:300px; width:100%">
                 <div class="centered">
                <a href="#" style="text-decoration:none;color:#FFBFFF; font-size:x-large"><strong>OWERRI</strong></a>
                <h3 style="color:#FFBFFF">&nbsp;&nbsp;&nbsp;{{count_number_owerri}}</h3>
             </div>
      </div>
    <div class="row" style="margin-top:1%">
        <div class="col-sm-4">
            <img src = "{% static 'pictures/ph.jpg '%}" class="img-fluid" style="height:300px; width:100%">
            <div class="centered">
                <a href="#" style="text-decoration:none;color:#FFBFFF; font-size:x-large"><strong>PORTHARCOURT</strong></a>
                <h3 style="color:#FFBFFF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{count_number_portharcourt}}</h3>
        </div>
        </div>
         <div class="col-sm-4">
             <img src = "{% static 'pictures/delta.jpg '%}" class="img-fluid" style="height:300px; width:100%">
             <div class="centered">
                <a href="#" style="text-decoration:none;color:#FFBFFF; font-size:x-large"><strong>DELTA</strong></a>
                <h3 style="color:#FFBFFF">&nbsp;&nbsp;&nbsp;{{count_number_delta}}</h3>
         </div>
         </div>
             <div class="col-sm-4">
                <img src = "{% static 'pictures/calabar.jpg '%}" class="img-fluid" style="height:300px; width:100%">
                 <div class="centered">
                <a href="#" style="text-decoration:none;color:#FFBFFF; font-size:x-large"><strong>CALABAR</strong></a>
                <h3 style="color:#FFBFFF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{count_number_calabar}}</h3>
             </div>
    </div>
    <div class="row" style="margin-top:1%">
        <div class="col-sm-4">
           <img src = "{% static 'pictures/uyo.jpg '%}" class="img-fluid" style="height:300px; width:100%" >
            <div class="centered">
                <a href="#" style="text-decoration:none;color:#FFBFFF; font-size:x-large"><strong>UYO</strong></a>
                <h3 style="color:#FFBFFF">&nbsp;&nbsp;&nbsp;{{count_number_uyo}}</h3>
        </div>
        </div>
         <div class="col-sm-4">
             <img src = "{% static 'pictures/ENUGU.jpg '%}" class="img-fluid" style="height:300px; width:100%">
             <div class="centered">
                <a href="#" style="text-decoration:none;color:#FFBFFF; font-size:x-large"><strong>ENUGU</strong></a>
                <h3 style="color:#FFBFFF">&nbsp;&nbsp;&nbsp;{{count_number_enugu}}</h3>
         </div>
         </div>
             <div class="col-sm-4">
                 <img src = "{% static 'pictures/kano.jpg '%}"class="img-fluid" style="height:300px; width:100%" >
                 <div class="centered">
                <a href="#" style="text-decoration:none;color:#FFBFFF; font-size:x-large"><strong>KANO</strong></a>
                <h3 style="color:#FFBFFF">&nbsp;&nbsp;&nbsp;{{count_number_kano}}</h3>
             </div>
    </div>
</div>
{% endblock %}

Frontend/templates/Frontend/display_actions.html
{% extends 'base/frontend/base.html' %}
{% load static %}

{% block content %}
<div class="container" style="padding-top:15px" >
    <div class="card col-md-12">
        <div class="row">

            <div class="col-md-4">
                {% for category in room_category  %}
                    {% if request.user.is_authenticated%}
                        <h2 class="h5">{{user.username}}</h2><span>Here are the steps you took in Reserving a room</span>
                    {% endif %}
                                <a href="#"><img src="{{ category.category_name.url }}" class="card-img-top img-fluid"style="height:180px"> </a>
                                <h4>{{category.category_name}}</h4>
                                <div class="col-lg-6 offset-3">
                                    <a href="#" class="btn btn-primary">View Hotel</a>
                                </div>

                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock%}

Frontend/templates/Frontend/findcity.html
{% extends 'base/frontend/base.html' %}
{% load static %}

{% block content %}
<div class="container" style="padding-top:15px" >
    <div class="row">

        <div class="col-md-4">
            {% for hotels in  check_for_city  %}

                        <a href="#"><img src="{{ hotels.hotel_image.url }}" class="card-img-top img-fluid"style="height:180px"> </a>
                        <h4>{{hotels.hotel_name}}</h4>
                        <h5>{{hotels.brief_description}}</h5>
                        <div class="col-lg-6 offset-3">
                            <a href="{% url 'Frontend:view_more' hotels.id%}"class="btn btn-primary">View Hotel</a>
                        </div>

            {% endfor %}
        </div>
    </div>
</div>
{% endblock%}

Frontend/templates/Frontend/home.html
{% extends 'base/frontend/base.html' %}
{% load static %}
    {% block content %}
        <!--IMAGE SLIDER-->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/css/gijgo.min.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-datepicker/css/bootstrap-datepicker.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-datepicker/css/bootstrap-datepicker.standalone.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap-datepicker/css/bootstrap-datepicker3.css' %}" />

<style>
     .centered {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
</style>

<div id="slides" class="carousel slide" data-ride="carousel">
            <ul class="carousel-indicators">
                <li data-target="#slides" data-slide-to="0" class="active"></li>
                <li data-target="#slides" data-slide-to="1"></li>
                <li data-target="#slides" data-slide-to="2"></li>
            </ul>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src = "{% static 'pictures/hotelbackground1.jpg '%}" class="img-fluid" style="height:400px; width:100%">
                    <div class="carousel-caption " style="padding-bottom:0px;padding-top:0px;bottom:40%;left:0%;right:0%">
                        <h1 class="display-2" style="color:black">Hotels</h1>
                        <h3 style="color:black">Hotels In Nigeria</h3>
                        <a href="{% url 'Frontend:cities' %}" class="btn btn-outline-light btn-lg btn-primary"
                           style="background-color:#FFBFFF">CITIES </a>
                        <button type="button" class="btn btn-primary btn-lg">FIND HOTELS</button>
                    </div>
                </div>
                  <div class="carousel-inner">
                <div class="carousel-item">
                    <img src = "{% static 'pictures/hotelbackground2.jpg '%}" class="img-fluid" style="height:400px; width:100%">
                    <div class="carousel-caption " style="padding-bottom:0px;padding-top:0px;bottom:40%;left:0%;right:0%">
                        <h1 class="display-2" style="color:black">Hotels</h1>
                        <h3 style="color:black">Hotels In Nigeria</h3>
                        <a href="{% url 'Frontend:cities' %}" class="btn btn-outline-light btn-lg btn-lg btn-primary"
                           style="background-color:#FFBFFF">CITIES</a>
                        <button type="button" class="btn btn-primary btn-lg">FIND HOTELS</button>
                    </div>
                </div>
                        <div class="carousel-inner">
                <div class="carousel-item">
                    <img src = "{% static 'pictures/hotelbackground3.jpg '%}" class="img-fluid" style="height:400px; width:100%">
                    <div class="carousel-caption " style="padding-bottom:0px;padding-top:0px;bottom:40%;left:0%;right:0%">
                        <h1 class="display-2"  style="color:black">Hotels</h1>
                        <h3 style="color:black">Hotels In Nigeria</h3>
                        <a href="{% url 'Frontend:cities' %}" class="btn btn-outline-light  btn-primary"
                           style="background-color:#FFBFFF">CITIES </a>
                        <button type="button" class="btn btn-primary btn-lg">FIND HOTELS</button>
                    </div>
                </div>
            </div>
                  </div>
        </div>
        </div>

    <div class="card col-lg-8 offset-2" style="background-color:grey;margin-top:-3%; min-height:100px !important;box-shadow:10px 10px 10px">

                        <div class="row" style="margin-top:2%">
                             <div class="col-lg-12" style="margin-top:2%">
                                    <form class="form-inline" method="POST" action="{% url 'Frontend:findcity' %}">
                                    {% csrf_token %}
                                        <div class="col-lg-3 form-group mb-2">

                                    <input type="text" class="form-control" placeholder="Search cities" name="cities" required>
                                     </div>
                                        <div class="col-lg-3 form-group mb-2" style="padding-left:1px; padding-right:1px">
                                    <input id="datepicker" width="100%" name="date" placeholder="check in"/>
                                 </div>
                                    <div class="col-lg-3 form-group mb-2" style="padding-left:1px; padding-right:1px">
                                    <input id="datepick" width="100%" name="date" placeholder="check-out"/>
                                </div>
                                        <div class="col-lg-3 form-group mb-2">

                                        <button class="btn btn-lg btn-primary form-control" style="height:40px">Find</button>

                                        </div>
                                    </form>
                        </div>
                        </div>
                        </div>
                        <!--Welcome-->
                    <div>

                    </div>
        <div class="container-fluid padding" style="padding-bottom:35px;padding-top:35px;top:40%;left:0%;right:0%">
            <div class="row welcome text-center">
                <div class="col-12">
                    <h1 class="display-4">LBMG-Online. </h1>
                </div>
                <hr>
                <div class="col-12">
                    <p class="lead">Welcome to LBMG-Online Website!
                        This site is filled with Luxurious hotels across Nigeria in High-Brow cities.
                    </p>
                </div>
            </div>
        </div>
        <!--Three Column Section-->
        <div class="container-fluid padding">
            <div class="row text-center padding">
                <div class="col-xs-12 col-xm-6 col-md-3">
                    <i class="fas fa-swimming-pool"></i>
                    <h3>Swimming-Pool</h3>
                    <a class = "navbar-brand" href = "#"><img src = "{% static 'pictures/Swimming.jpg '%}" class="img-fluid" height="100px" width="150"/></a>
                    <P>Olympic size swimming pool<br>
                        "Water is home, just dive in"</P>
                </div>
                <div class="col-xm-12 col-md-3">
                    <i class="fas fa-superpowers"></i>
                    <h3>Gym</h3>
                    <a class = "navbar-brand" href = "#"><img src = "{% static 'pictures/gym.jpg '%}" class="img-fluid" height="100px" width="150"/></a>
                    <P>Modern Gym facilities<br>
                        "get fit, work out"</P>
                </div>
                <div class="col-xm-12 col-md-3">
                    <i class="fas fa-utensils"></i>
                    <h3>Food</h3>
                    <a class = "navbar-brand" href = "#"><img src = "{% static 'pictures/food.jpg '%}" class="img-fluid" height="100px" width="150"/></a>
                    <P>Yummy Nigerian Dishes<br>
                        "good food, is good mood"</P>
                </div>
                <div class="col-xm-12 col-md-3">
                    <i class="fab fa-glass-martini"></i>
                    <h3>Bar</h3>
                    <a class = "navbar-brand" href = "#"><img src = "{% static 'pictures/bar.jpg '%}" class="img-fluid" height="100px" width="150"/></a>
                    <P>From cocktails to liquor,wines and spirits<br>
                        "Let the evening begin"</P>
                </div>
            </div>

            <!--Connect-->
            <div class="container-fluid padding">
                <div class=" row text-center padding">
                    <div class="col-12">
                        <h2>Connect</h2>
                    </div>
                    <div class="col-md-10 offset-1 social-pading">
                        <a href="https://www.facebook.com/sharer/sharer.php?u=http://CodingForEntrepreneurs.com/">
                <i class="fab fa-facebook-square fa-2x" style="color: #3B5998"></i>
            </a>
            <a href="" ><i class="fab fa-google-plus-square fa-2x" style="color: #dc4e41"></i></a>
            <a href=""  ><i class="fab fa-twitter-square fa-2x" style="color: #55acee"></i></a>
            <a href="" ><i class="fab fa-linkedin fa-2x" style="color:  #0077B5"></i></a>
            <a href=""><i class="fab fa-whatsapp-square fa-2x" style="color: #25d366"></i></a>
                    </div>
                </div>
            </div>
               <!--footer-->
    <footer>
        <div class="container-fluid padding">
            <div class="row text-center">
                <div class="col-lg-12">
                    <p> copyright@LBMG2018</p>

                </div>

            </div>

        </div>
    </footer>
        </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src = "https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
<script src="{%static 'bootstrap-4.1.1-dist/js/bootstrap.min.js' %}" type="text/javascript">
</script>
<script type="text/javascript" src="{% static 'bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.6/js/gijgo.min.js" type="text/javascript"></script>
<script>
    $('#datepicker').datepicker({
        uiLibrary: 'bootstrap4',
        format: "yyyy-mm-dd",
        multidate: true,
        multidateSeparator: "-",
    });
</script>
<script>
    $('#datepick').datepicker({
        uiLibrary: 'bootstrap4',
        format: "yyyy-mm-dd",
        multidate: true,
        multidateSeparator: "-",
    });
</script>
<script>
    $('#datepk').datepicker({
        uiLibrary: 'bootstrap4',
        format: "yyyy-mm-dd",
        multidate: true,
        multidateSeparator: "-",
    });
</script>
<script>
    $('#datepic').datepicker({
        uiLibrary: 'bootstrap4',
        format: "yyyy-mm-dd",
        multidate: true,
        multidateSeparator: "-",
    });
</script>
<script>
    $('#datepc').datepicker({
        uiLibrary: 'bootstrap4',
        format: "yyyy-mm-dd",
        multidate: true,
        multidateSeparator: "-",
    });
</script>
<script>
    $('#datepck').datepicker({
        uiLibrary: 'bootstrap4',
        format: "yyyy-mm-dd",
        multidate: true,
        multidateSeparator: "-",
    });
</script>
    {% endblock %}